### ISSUE TITLE
haproxy version not found

### ISSUE THREAD

**Issue by akerekes** [uzyexe/dockerfile-marathon-servicerouter#1]
I've tried to build the image by `docker build .` but it failed with:

```
E: Version '1.5.8-3' for 'haproxy' was not found
```

After setting the version to `1.5.8-3+deb8u2` it worked.

**Comment by uzyexe** [comment]
hi, @akerekes 

Thank you for reporting. :+1: 
Fixed this issue. latest image has been pushed to Docker Hub.
https://hub.docker.com/r/uzyexe/marathon-servicerouter/

and Add tag, and image Add Marathon `v0.10.1` was.
https://hub.docker.com/r/uzyexe/marathon-servicerouter/tags/

thx!
