### ISSUE TITLE
where are the haproxy logs?

### ISSUE THREAD

**Issue by akerekes** [uzyexe/dockerfile-marathon-servicerouter#6]
I'm trying to debug my setup, but not able to find the logs generated by haproxy, only the output from servicerouter. I've looked in the output of the container, the syslog of the host, and the /var/log directory of the container. Any suggestions?

**Comment by uzyexe** [comment]
Hi, @akerekes

Thank you for reporting!
I was add rsyslog service.
It can be found in `/var/log/haproxy/haproxy.log`
